# Data Cleaning

library(data.table)
library(ggplot2)
#loading the data
data = read.csv("~/Desktop/BioStat2/Final Project/rhc.csv", sep=",")

#no of comorbid illnesses
data$no_comorbid <- data$cardiohx + data$chfhx + data$dementhx + data$psychhx + data$chrpulhx + data$renalhx + data$liverhx + data$gibledhx + data$malighx + data$immunhx + data$transhx + data$amihx

#selecting variables only mentioned in Table 1
data = subset(data, select = c(age,sex,race,cat1,ca,dnr1,aps1,surv2md1,no_comorbid,adld3p,das2d3pc,temp1,hrt1,meanbp1,resp1,wblc1,wblc1,paco21,ph1,crea1,alb1,scoma1,swang1))

#renaming columns
colnames(data) <- c("age", "sex", "race", "primary_disease_cat","cancer","dnr","apache","prob_2mo_survival","no_comorbid","adl","dasi","temp","heart_rate","blood_pressure","resp_rate","wbc","PaO2/FIO2","PaCo2","ph","creatinine","albumin","glasgow_coma","rch")

#creatiing age group
setDT(data)[age <50, agegroup := "<50"]
data[age >=50 & age <60, agegroup := "50 to <60"]
data[age >=60 & age <70, agegroup := "60 to <70"]
data[age >=70 & age <80, agegroup := "70 to <80"]
data[age >=80, agegroup := ">=80"]

#creating disease category
setDT(data)[primary_disease_cat=="ARF", primary_dis_cat := "ARF"]
data[primary_disease_cat=="MOSF w/Malignancy" | primary_disease_cat=="MOSF w/Sepsis", primary_dis_cat := "MOSF"]
data[primary_disease_cat=="CHF", primary_dis_cat := "CHF"]
data[primary_disease_cat=="Cirrhosis" |primary_disease_cat=="Colon Cancer" |primary_disease_cat=="Coma" |primary_disease_cat=="COPD" |primary_disease_cat=="Lung Cancer", primary_dis_cat := "Other"]

#removing age and primary_disease
data = subset(data, select = -c(age,primary_disease_cat))



# Graphs of Variable 1-6

## Barplot of Sex
ggplot(data,aes(x=sex,fill=rch,group=rch)) +
  geom_bar() +
  labs(title="Barplot of Sex")

ggplot(data,aes(x=sex,fill=rch,group=rch)) +
  facet_grid(rch ~ .) +
  geom_bar() +
  labs(title="Barplot of Sex")

## Barplot of Race
ggplot(data,aes(x=race,fill=rch,group=rch)) +
  geom_bar() +
  labs(title="Barplot of Race")

ggplot(data,aes(x=race,fill=rch,group=rch)) +
  facet_grid(rch ~ .) +
  geom_bar() +
  labs(title="Barplot of Race")

## Barplot of Cancer
ggplot(data,aes(x=cancer,fill=rch,group=rch)) +
  geom_bar() +
  labs(title="Barplot of Cancer")

ggplot(data,aes(x=cancer,fill=rch,group=rch)) +
  facet_grid(rch ~ .) +
  geom_bar() +
  labs(title="Barplot of Cancer")

## Barplot of DNR Status
ggplot(data,aes(x=dnr,fill=rch,group=rch)) +
  geom_bar() +
  labs(title="Barplot of DNR Status")

ggplot(data,aes(x=dnr,fill=rch,group=rch)) +
  facet_grid(rch ~ .) +
  geom_bar() +
  labs(title="Barplot of DNR Status")

## Density Plot of APACHE III Score
ggplot(data,aes(x=apache,fill=rch,group=rch)) +
  geom_density(alpha=.25)+
  labs(title="Density Plot of APACHE III Score")

ggplot(data,aes(x=apache,fill=rch,group=rch)) +
  facet_grid(rch ~ .) +
  geom_density(alpha=.25)+
  labs(title="Density Plot of APACHE III Score")


## Density Plot of Prob of 2-mo Survival
ggplot(data,aes(x=prob_2mo_survival,fill=rch,group=rch)) +
  geom_bar() +
  geom_density(alpha=.25)+
  coord_cartesian(ylim=c(0,3), xlim = c(0,1))+
  labs(title="Density Plot of Prob of 2-mo Survival")

ggplot(data,aes(x=prob_2mo_survival,fill=rch,group=rch)) +
  facet_grid(rch ~ .) +
  geom_bar() +
  geom_density(alpha=.25)+
  coord_cartesian(ylim=c(0,3), xlim = c(0,1))+
  labs(title="Density Plot of Prob of 2-mo Survival")
