---
title: "Biostat_proj_q2"
author: "Jieun Park"
date: "3/28/2018"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Create and manipulate data for use

```{r}
data <- read.csv('/Users/jieun/Desktop/Biostat2/rhc.csv')

#loading the data

#no of comorbid illnesses
data$no_comorbid <- data$cardiohx + data$chfhx + data$dementhx + data$psychhx + data$chrpulhx + data$renalhx + data$liverhx + data$gibledhx + data$malighx + data$immunhx + data$transhx + data$amihx 

#selecting variables only mentioned in Table 1 but not adl as most values are missing
data = subset(data, select = c(age,sex,race,death,edu,income,ninsclas,cat1,ca,dnr1,aps1,surv2md1,no_comorbid,das2d3pc,temp1,hrt1,meanbp1,resp1,wblc1,wblc1,paco21,ph1,sod1,pot1,hema1,bili1,crea1,alb1,scoma1,swang1))

#renaming columns
colnames(data) <- c("age", "sex","race","death","education","income","medical_insurance","primary_disease_cat","cancer","dnr","apache","prob_2mo_survival","no_comorbid","dasi","temp","heart_rate","blood_pressure","resp_rate","wbc","PaO2_FIO2","PaCo2","ph","sodium","potassium","hematocrit","bilirubin","creatinine","albumin","glasgow_coma","rch")

#creatiing age group
setDT(data)[age <50, agegroup := "<50"]
data[age >=50 & age <60, agegroup := "50 to <60"]
data[age >=60 & age <70, agegroup := "60 to <70"]
data[age >=70 & age <80, agegroup := "70 to <80"]
data[age >=80, agegroup := ">=80"]

#creating disease category
setDT(data)[primary_disease_cat=="ARF", primary_dis_cat := "ARF"]
data[primary_disease_cat=="MOSF w/Malignancy" | primary_disease_cat=="MOSF w/Sepsis", primary_dis_cat := "MOSF"]
data[primary_disease_cat=="CHF", primary_dis_cat := "CHF"]
data[primary_disease_cat=="Cirrhosis" |primary_disease_cat=="Colon Cancer" |primary_disease_cat=="Coma" |primary_disease_cat=="COPD" |primary_disease_cat=="Lung Cancer", primary_dis_cat := "Other"]

#removing age and primary_disease
data = subset(data, select = -c(primary_disease_cat))

data=data[complete.cases(data)]

data$death <- as.factor(ifelse(data$death == "Yes", 1, 0))
```

```{r}
fit <- glm(rch ~ blood_pressure+heart_rate+resp_rate+ph+PaO2_FIO2+PaCo2+primary_dis_cat, data = data, family = binomial)

summary(fit)

test <- lm(blood_pressure~rch,data)
anova(test)
```















