```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(ggplot2)
library(data.table)
library(lmtest)
library(sandwich)
```

## Create and manipulate data for use

```{r}
#loading the raw data
data <- read.csv('/Users/jieun/Desktop/Biostat2/rhc.csv')
# Check NA values for each column
sapply(data,function(x) sum(is.na(x)))

levels(data$cat2)
data$cat2 <- as.character(data$cat2)

# Change NA values of secondary disease to "none"
data$cat2 <- ifelse(is.na(data$cat2),"none",data$cat2)
data$cat2 <- as.factor(data$cat2)


#no of comorbid illnesses
data$no_comorbid <- data$cardiohx + data$chfhx + data$dementhx + data$psychhx + data$chrpulhx + data$renalhx + data$liverhx + data$gibledhx + data$malighx + data$immunhx + data$transhx + data$amihx 

#selecting variables only mentioned in Table 1 but not adl as most values are missing
data <- data %>%
  select(-c(X,cat2,adld3p,sadmdte,dschdte,dthdte,lstctdte,t3d30,dth30,ptid,urin1))

names(data)
str(data$survivalProb)
#renaming columns
colnames(data) <- c("primary_disease_cat","cancer","death","cardio_com",   "heartfailure_com","dementia_com","psychiatric_com","pulmonary_com","renal_com","Cirrhosis_com","GIbleed_com","malign_com","immune_com","transfer_com","myocardio_com","age","sex",         "education","survivalProb","DASI","APACHEscore","glasgow","bloodPressure","wbc","heartRate","respRate","temperature","PaO2FIO2ratio","albumin","hematocrit","bilirubin",       "creatinine","sodium","potassium","PaCo2","PH","rhc","weight", "DNR","medicalInsurance","respDiag","cardioDiag","neuroDiag","gastroDiag","renalDiag","metaDiag","hemaDiag","sepsisDiag","traumaDiag","orthoDiag","race","income","no_comorbid")

data$cardio_com <- as.factor(data$cardio_com)
data$heartfailure_com <- as.factor(data$heartfailure_com)
data$dementia_com <- as.factor(data$dementia_com)
data$psychiatric_com <- as.factor(data$psychiatric_com)
data$pulmonary_com <- as.factor(data$pulmonary_com)
data$renal_com <- as.factor(data$renal_com)
data$Cirrhosis_com <- as.factor(data$Cirrhosis_com)
data$GIbleed_com <- as.factor(data$GIbleed_com)
data$malign_com <- as.factor(data$malign_com)
data$immune_com <- as.factor(data$immune_com)
data$transfer_com <- as.factor(data$transfer_com)
data$myocardio_com <- as.factor(data$myocardio_com)

#creating age group
setDT(data)[age <50, agegroup := "<50"]
data[age >=50 & age <60, agegroup := "50 to <60"]
data[age >=60 & age <70, agegroup := "60 to <70"]
data[age >=70 & age <80, agegroup := "70 to <80"]
data[age >=80, agegroup := ">=80"]

data$agegroup <- as.factor(data$agegroup)

#creating disease category
setDT(data)[primary_disease_cat=="ARF", primary_dis_cat := "ARF"]
data[primary_disease_cat=="MOSF w/Malignancy" | primary_disease_cat=="MOSF w/Sepsis", primary_dis_cat := "MOSF"]
data[primary_disease_cat=="CHF", primary_dis_cat := "CHF"]
data[primary_disease_cat=="Cirrhosis" |primary_disease_cat=="Colon Cancer" |primary_disease_cat=="Coma" |primary_disease_cat=="COPD" |primary_disease_cat=="Lung Cancer", primary_dis_cat := "Other"]

data$primary_dis_cat <- as.factor(data$primary_dis_cat)

#removing age and primary_disease
data = subset(data, select = -c(age,primary_disease_cat))

# Check NA values for each column
sapply(data,function(x) sum(is.na(x)))

data$death <- as.factor(ifelse(data$death == "Yes", 1, 0))

```

```{r}

# Model to predict whether a patient will receive RHC as a function of all pre-RHC variables

fit <- glm(rhc ~ agegroup + sex + education + race + income + weight + primary_dis_cat + cancer + cardio_com + heartfailure_com + dementia_com + psychiatric_com + pulmonary_com + renal_com + Cirrhosis_com + GIbleed_com + malign_com + immune_com + transfer_com + myocardio_com + DASI + APACHEscore + glasgow + bloodPressure + wbc + heartRate + respRate + temperature + PaO2FIO2ratio + albumin + hematocrit + bilirubin + creatinine + sodium + potassium + PaCo2 + PH + DNR + medicalInsurance + respDiag + cardioDiag + neuroDiag + gastroDiag + renalDiag + metaDiag + hemaDiag + sepsisDiag + traumaDiag + orthoDiag, data=data, family="binomial")


# summary(fit)

dfp <- function(p.val){
  format.pval(pv = p.val, eps = 0.001, nsmall = 3)
}

Coefficient <- round(summary(fit)$coefficients[,1], 3)
p.value <- dfp(round(summary(fit)$coefficients[,4], 3))

x <- cbind(Coefficient, p.value)
knitr::kable(x, align = "c")




## Final model for the treatment (RHC) only including significant 

fit_2 <- glm(rhc ~ agegroup + education + weight + primary_dis_cat + cancer + dementia_com
 + psychiatric_com + transfer_com + APACHEscore + bloodPressure + heartRate + respRate + PaO2FIO2ratio + hematocrit + sodium + potassium + PaCo2 + PH + DNR + medicalInsurance + respDiag + cardioDiag + neuroDiag + gastroDiag + renalDiag + hemaDiag + sepsisDiag + traumaDiag,data=data,family="binomial")

summary(fit_2)

```



```{r}
# compare between fit and fit_2
# using Cross entropy and AUC

n <- nrow(data)
set.seed(123)
train<- sample(n, n*0.7)

dtrain<- data[train,]
dtest<- data[-train,]

pred1test <- predict(fit, newdata = dtest, type = 'response')
pred2test <- predict(fit_2, newdata = dtest, type = 'response')

CE_test1<--(mean(as.numeric(dtest$death) * log(pred1test) + (1-as.numeric(dtest$death)) * log(1 - pred1test)))
CE_test2<--(mean(as.numeric(dtest$death) * log(pred2test) + (1-as.numeric(dtest$death)) * log(1 - pred2test)))

t <- cbind(CE_test1, CE_test2)
knitr::kable(t)

library(pROC)

roc1test<-roc(dtest$death~pred1test)
roc2test<-roc(dtest$death~pred2test) 

p1 <- plot(roc1test, print.thres=TRUE,print.auc=TRUE, col=1, main="ROC of model 1 test")

p2 <- plot(roc2test,print.thres=TRUE, print.auc=TRUE, col=4, main="ROC of model 2 test")

```
