---
title: "Untitled"
author: "Peter Kim"
date: "4/7/2018"
output:
  word_document: default
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, include=FALSE, echo=FALSE}
library(data.table)
library(ggplot2)
library(magrittr)
library(officer)
library(docxtools)
library(docxtractr)
library(tidyverse)
library(tableone)
library(qwraps2)
```

```{r, include=FALSE, echo=FALSE}

#loading the raw data
data <- read.csv('~/Desktop/Spring2018_Biostatistics2_Final-master/rhc.csv')
# Check NA values for each column
sapply(data,function(x) sum(is.na(x)))

levels(data$cat2)
data$cat2 <- as.character(data$cat2)

# Change NA values of secondary disease to "none"
data$cat2 <- ifelse(is.na(data$cat2),"none",data$cat2)
data$cat2 <- as.factor(data$cat2)

#no of comorbid illnesses
data$no_comorbid <- data$cardiohx + data$chfhx + data$dementhx + data$psychhx + data$chrpulhx + data$renalhx + data$liverhx + data$gibledhx + data$malighx + data$immunhx + data$transhx + data$amihx 

#selecting variables only mentioned in Table 1 but not adl as most values are missing
data <- data %>%
  select(-c(X,adld3p,sadmdte,dschdte,dthdte,lstctdte,t3d30,dth30,ptid,urin1))

names(data)

#renaming columns
colnames(data) <- c("primary_disease_cat","secondary_disease_cat","cancer","death","cardio_com",   "heartfailure_com","dementia_com","psychiatric_com","pulmonary_com","renal_com","Cirrhosis_com","GIbleed_com","malign_com","immune_com","transfer_com","myocardio_com","age","sex",         "education","survivalProb","DASI","APACHEscore","glasgow","bloodPressure","wbc","heartRate","respRate","temperature","PaO2FIO2ratio","albumin","hematocrit","bilirubin",       "creatinine","sodium","potassium","PaCo2","PH","rhc","weight", "DNR","medicalInsurance","respDiag","cardioDiag","neuroDiag","gastroDiag","renalDiag","metaDiag","hemaDiag","sepsisDiag","traumaDiag","orthoDiag","race","income","no_comorbid")

#creatiing age group
setDT(data)[age <50, agegroup := "<50"]
data[age >=50 & age <60, agegroup := "50 to <60"]
data[age >=60 & age <70, agegroup := "60 to <70"]
data[age >=70 & age <80, agegroup := "70 to <80"]
data[age >=80, agegroup := ">=80"]

#creating disease category
setDT(data)[primary_disease_cat=="ARF", primary_dis_cat := "ARF"]
data[primary_disease_cat=="MOSF w/Malignancy" | primary_disease_cat=="MOSF w/Sepsis", primary_dis_cat := "MOSF"]
data[primary_disease_cat=="CHF", primary_dis_cat := "CHF"]
data[primary_disease_cat=="Cirrhosis" |primary_disease_cat=="Colon Cancer" |primary_disease_cat=="Coma" |primary_disease_cat=="COPD" |primary_disease_cat=="Lung Cancer", primary_dis_cat := "Other"]

#removing age and primary_disease
data = subset(data, select = -c(age,primary_disease_cat))

# Check NA values for each column
sapply(data,function(x) sum(is.na(x)))

data$death <- as.factor(ifelse(data$death == "Yes", 1, 0))
```

```{r, echo=FALSE, include=FALSE}
options(qwraps2_markup = "markdown")
args(summary_table)
dat1 <- data %>%
  filter(rhc=="RHC")

dat2 <- data %>%
  filter(rhc=="No RHC")
our_summary1 <- 
  list("APACHEscore" = 
         list("APACHEscore mean (sd)" = ~ qwraps2::mean_sd(APACHEscore),
              "APACHEscore median (iqr)" = ~ qwraps2::median_iqr(APACHEscore)),
       "survivalProb" = 
         list("survivalProb mean (sd)" = ~ qwraps2::mean_sd(survivalProb),
              "survivalProb median (iqr)" = ~ qwraps2::median_iqr(survivalProb)),
       "no_comorbid" = 
         list("no_comorbid mean (sd)" = ~ qwraps2::mean_sd(no_comorbid),
              "no_comorbid median (iqr)" = ~ qwraps2::median_iqr(no_comorbid)),
       "DASI" = 
         list("DASI mean (sd)" = ~ qwraps2::mean_sd(DASI),
              "DASI median (iqr)" = ~ qwraps2::median_iqr(DASI)),
       "temperature" = 
         list("temperature mean (sd)" = ~ qwraps2::mean_sd(temperature),
              "temperature median (iqr)" = ~ qwraps2::median_iqr(temperature)),
       "heartRate" = 
         list("heartRate mean (sd)" = ~ qwraps2::mean_sd(heartRate),
              "heartRate median (iqr)" = ~ qwraps2::median_iqr(heartRate)),
       "bloodPressure" = 
         list("bloodPressure mean (sd)" = ~ qwraps2::mean_sd(bloodPressure),
              "bloodPressure median (iqr)" = ~ qwraps2::median_iqr(bloodPressure)),
       "respRate" = 
         list("respRate mean (sd)" = ~ qwraps2::mean_sd(respRate),
              "respRate median (iqr)" = ~ qwraps2::median_iqr(respRate)),
       "wbc" = 
         list("wbc mean (sd)" = ~ qwraps2::mean_sd(wbc),
              "wbc median (iqr)" = ~ qwraps2::median_iqr(wbc)),
       "PaO2FIO2ratio" = 
         list("PaO2FIO2ratio mean (sd)" = ~ qwraps2::mean_sd(PaO2FIO2ratio),
              "PaO2FIO2ratio median (iqr)" = ~ qwraps2::median_iqr(PaO2FIO2ratio)),
       "PaCo2" = 
         list("PaCo2 mean (sd)" = ~ qwraps2::mean_sd(PaCo2),
              "PaCo2 median (iqr)" = ~ qwraps2::median_iqr(PaCo2)),
       "PH" = 
         list("PH mean (sd)" = ~ qwraps2::mean_sd(PH),
              "PH median (iqr)" = ~ qwraps2::median_iqr(PH)),
       "creatinine" = 
         list("creatinine mean (sd)" = ~ qwraps2::mean_sd(creatinine),
              "creatinine median (iqr)" = ~ qwraps2::median_iqr(creatinine)),
       "albumin" = 
         list("albumin mean (sd)" = ~ qwraps2::mean_sd(albumin),
              "albumin median (iqr)" = ~ qwraps2::median_iqr(albumin)),
       "glasgow" = 
         list("glasgow mean (sd)" = ~ qwraps2::mean_sd(glasgow),
              "glasgow median (iqr)" = ~ qwraps2::median_iqr(glasgow))

  ) 

grouped <- summary_table(dplyr::group_by(data, rhc),  our_summary1)
grouped
```

```{r, echo=FALSE}
knitr::kable(grouped, align = "c")
```

